create table posts (
    id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	company_id integer references companies(id),
    title varchar(255) NOT NULL,
    description text,
    image varchar(255),
	category varchar(255)
); 
